services:
  pryx:
    build: .
    container_name: pryx
    ports:
      - 8080:8080
    environment:
      API_KEY: ${API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DB_AUTOMIGRATE: ${DB_AUTOMIGRATE}
      ADMIN_SECRET: ${ADMIN_SECRET}

  pryx-migrate:
    build: .
    container_name: pryx-migrate
    command: ["/app/migrate"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
