name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Go vet, test, and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Go env
        run: go env

      - name: Vet
        run: go vet ./...

      - name: Test
        env:
          CGO_ENABLED: 1
        run: |
          go test ./... -cover -race

      - name: Build pryx (api)
        env:
          CGO_ENABLED: 0
        run: go build -o dist/pryx cmd/app/main.go

      - name: Build migrate
        env:
          CGO_ENABLED: 0
        run: go build -o dist/migrate cmd/migrate/main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pryx-binaries
          path: |
            dist/pryx
            dist/migrate
